### ISSUE TITLE
`vnpm` doesn't install the selected library and quits without any information when I press enter

### ISSUE THREAD

**Issue by Gu-Miao** [webfansplz/vtui-npm#12]
I've installed `vtui-npm` long ago and successfully ran it. It's fun and convenient. But when I run it today, it doesn't work correctly. See this gif:

![Honeycam 2022-12-20 12-17-34](https://user-images.githubusercontent.com/28031505/208583325-d6b28f29-5365-4896-9fce-459d33fbdf78.gif)

My `vtui-npm` version is `0.0.1`. I'd like to offer more information. But as you see, there's nothing but the blank screen.

**Comment by Gu-Miao** [comment]
Some update:
I finally got the error log: 

![image](https://user-images.githubusercontent.com/28031505/208820053-31c73831-de13-4fa3-80ee-64f48d511256.png)

```
Error: Unsupported agent "null"
at getCommand (file:///D:/nvm/node_global/node_modules/vtui-npm/node_modules/@antfu/ni/dist/shared/ni.e5a4e327.mjs:426:11)
at parseNi (file:///D:/nvm/node_global/node_modules/vtui-npm/node_modules/@antfu/ni/dist/shared/ni.e5a4e327.mjs:446:12)
at G (file:///D:/nvm/node_global/node_modules/vtui-npm/dist/main.mjs:1:9105)
at asynco (file:///D:/nvm/node_global/node_modules/vtui-npm/dist/main.mjs:1:9509)
```

**Comment by webfansplz** [comment]
Do you installed the npm package management library ? .e.g.  pnpm/yarn/npm

**Comment by Gu-Miao** [comment]
I installed all of them using npm.
